broaden type check to include numpy scalars (in addition to `ndarray`)
stan-dev/cmdstanpy pull request #356
Opened 2021-03-05 22:24 UTC by meereeum

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

JSON serialization currently falls down if the `data` dictionary values include numpy scalars (with `TypeError: $SCALAR is not JSON serializable`). Fix type-check to catch these, in addition to arrays (the `tolist()` conversion still works as expected to convert to builtin `int`/`float`).

#### Copyright and Licensing

I am the copyright holder of this work and agree to the terms of the license.

2021-03-06 21:36 UTC, mitzimorris commented
could you please file an issue for this and say a little bit more about the data that is problematic?
I'm not sure this fix is going to do the right thing for your data, so more context here would help.
we definitely want to be able to handle numpy data types correctly.

2021-03-07 05:02 UTC, meereeum commented
Sure, just imagine passing `N=np.int32(100)` as data to your favorite model. This is the default mode for data generated by, e.g., `pybrms`. I'm using this code on my personal branch as a prerequisite to be able to run `brms`-type models. There may be other ways to check for numpy scalars, but limiting to `np.ndarray` type for proper JSON serialization is too limiting.

2021-03-07 08:38 UTC, ahartikainen commented
This looks very neat solution.

2021-03-07 16:04 UTC, mitzimorris commented
the question is, has this been tested?  I think what will happen is that the input will be a list when the Stan program will expect N to be a scalar; therefore, I don't think this will work.  however, a unit test should be easy to construct using the example bernoulli model. 

while I really appreciate this PR, the process is:  file an issue, provide a test case showing how things should work, and then fix the bug.  it's a real PITA, but in the long run, it's worth it.

2021-03-07 16:15 UTC, ahartikainen commented
It will be scalar.

`np.int32(3).tolist() == 3`

2021-03-07 18:17 UTC, mitzimorris requested changes
please add two tests: 

- add unit test here:  https://github.com/stan-dev/cmdstanpy/blob/eba7d3b55a5f81dd422d7f696637fec672c864de/test/test_utils.py#L206. test is scalar
-  add functional test here:   https://github.com/stan-dev/cmdstanpy/blob/eba7d3b55a5f81dd422d7f696637fec672c864de/test/test_sample.py#L153-L161

2021-03-25 17:21 UTC, ahartikainen approved these changes

2021-03-25 17:47 UTC, mitzimorris approved these changes

2021-03-25 17:48 UTC, merged

2021-03-26 19:13 UTC, meereeum commented
thanks for seeing this through, @mitzimorris