Add `diagnose` method to `CmdStanModel`.
stan-dev/cmdstanpy pull request #734
Opened 2024-02-09 19:47 UTC by tillahoffmann

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

This PR adds the `diagnose` method to `CmdStanModel` which can be used to verify gradients, e.g., explicit gradients for custom functions implemented in C++. Documentation is based on the [equivalent `cmdstanr` function](https://mc-stan.org/cmdstanr/reference/model-method-diagnose.html) and other methods, such as `CmdStanModel.variational`.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Harvard University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

2024-02-09 20:38 UTC, WardBrian commented
How would you feel about modeling this more after the `log_prob` method on `CmdStanModel`? Namely, not needing its own Args class or a holder for the return type, but just giving you back the table as a pandas dataframe and that's it.

2024-02-09 21:35 UTC, tillahoffmann commented
Good point, updated. Only caveat is that if `required_gradients_ok` is `False`, there is no way to check if the gradients passed the checks. But this is likely to be used only interactively anyway so probably not a problem.

2024-02-09 21:54 UTC, WardBrian requested changes

2024-02-09 21:54 UTC, WardBrian commented on test/test_model.py
> +def test_diagnose():
Would you mind adding a test of the `inits` argument? Should be easy enough to test against `log_prob`, actually.

2024-02-09 21:54 UTC, WardBrian commented on cmdstanpy/model.py
> +            if proc.returncode:
The command could have failed for other reasons, like leaving out data for a model that requires it. 

I think to be safe, if there was a return code, to always display the value of `stderr`. 

We should also check that `output` exists before trying to read it, for this reason.

2024-02-09 21:54 UTC, WardBrian commented on cmdstanpy/model.py
> +            # Read the text and get the last chunk separated by a single # char.
[Comment] I'd never looked at the output of `diagnose` before, and wow is it not what I would have expected.

2024-02-09 22:31 UTC, tillahoffmann commented
Thanks for the comments, I'll have a look. As an aside, do we mind how close the interfaces of `cmdstanr` and `cmdstanpy` are? E.g., `cmdstanr` uses the object-oriented approach for `diagnose` (see [here](https://mc-stan.org/cmdstanr/reference/CmdStanDiagnose.html)). `cmdstanr` doesn't seem to implement `log_prob` (but I haven't dug too deep into the docs).

2024-02-09 22:49 UTC, WardBrian commented
I believe they have support for log_prob through some optional RCPP stuff, which is pretty far outside anything we’d want to do in Python.

We try to be consistent-ish for big things like the names and default values of the arguments to `sample`, but I don’t think it makes sense to aim for complete API matching, especially for smaller things like this

2024-02-12 16:26 UTC, WardBrian approved these changes
LGTM!

I'm going to hold off on merging this to see if anything comes in which would justify a 1.2.2 patch, but this will be in the next major version.

2025-02-03 19:26 UTC, bob-carpenter commented
@tillahoffmann:  Is this ready to merge?  

@WardBrian:  If it's ready to merge, would you mind taking another final look?

2025-02-03 20:23 UTC, tillahoffmann commented
Yes, I think this is ready to be merged.

2025-02-03 20:43 UTC, WardBrian approved these changes
Apologies for letting this slip -- my intention was that this would be merged before cmdstanpy 2.0.0, as we've stated that the next non-bugfix release would be 2.0.0 and contain the removal of our stated deprecations.

But, there is a lot of other work that needs to be done (primarily by me) to get to a 2.0.0, that I have been avoiding. 

I think this is fine to go in -- if we need another patch release before 2.0.0, we can either cherry-pick around this or just include it (even if it makes the semantic versioning gods angry).

Thanks again for the feature!

2025-02-03 20:44 UTC, merged